baseURL = 'https://breachline.app/'
languageCode = 'en-us'
title = 'BreachLine'
theme = 'breachline-theme'

[params]
  description = 'Powerful time series data analysis tool for cyber incident response investigations'
  author = 'BreachLine Team'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Features'
    url = '/features/'
    weight = 2
  [[menu.main]]
    name = 'Download'
    url = '/download/'
    weight = 3
  [[menu.main]]
    name = 'Pricing'
    url = '/pricing/'
    weight = 4
